services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v22.2.2
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS_ENABLED=true
      - REDPANDA_AUTO_CREATE_TOPICS_REPLICAS=1
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:9093

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
    ports:
      - "8080:8080"

  producer:
      build: ./producer
      restart: always
      depends_on:
        - redpanda